ALTER TABLE users ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system';
ALTER TABLE users ADD COLUMN updated_by VARCHAR(255) NOT NULL DEFAULT 'system';

ALTER TABLE products ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system';
ALTER TABLE products ADD COLUMN updated_by VARCHAR(255) NOT NULL DEFAULT 'system';

ALTER TABLE orders ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system';
ALTER TABLE orders ADD COLUMN updated_by VARCHAR(255) NOT NULL DEFAULT 'system';
